# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "FMB Motorcycle Parts Finder"
client_id = "982d48a1571687cb91b6310a490bbe9f"
application_url = "https://56e00a98-ad08-48da-8c00-1d8f49a92d07-00-32mevip0hcwqx.spock.replit.dev"
embedded = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://56e00a98-ad08-48da-8c00-1d8f49a92d07-00-32mevip0hcwqx.spock.replit.dev/api/auth/callback"
]

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[[extensions]]
type = "theme_app_extension"
name = "FMB Motorcycle Parts Extension"
handle = "fmb-motorcycle-parts"

[[extensions.targeting]]
target = "purchase.checkout.block.render"